In [7]:
pip install geopandas

Collecting geopandas
  Downloading geopandas-0.14.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 3.8 MB/s eta 0:00:01
Collecting shapely>=1.8.0
  Downloading shapely-2.0.1-cp39-cp39-macosx_10_9_x86_64.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 3.6 MB/s eta 0:00:01
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.9/site-packages (from geopandas) (21.3)
Requirement already satisfied: pandas>=1.4.0 in /opt/anaconda3/lib/python3.9/site-packages (from geopandas) (1.4.2)
Collecting pyproj>=3.3.0
  Downloading pyproj-3.6.1-cp39-cp39-macosx_10_9_x86_64.whl (6.1 MB)
     |████████████████████████████████| 6.1 MB 3.6 MB/s eta 0:00:01
Collecting fiona>=1.8.21
  Downloading Fiona-1.9.4.post1-cp39-cp39-macosx_10_15_x86_64.whl (18.6 MB)
     |████████████████████████████████| 18.6 MB 3.3 MB/s eta 0:00:01
Requirement already satisfied: click~=8.0 in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8.21->geopandas) (8.0.4)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8.21->geopandas) (2021.10.8)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: importlib-metadata in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8.21->geopandas) (4.11.3)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8.21->geopandas) (1.16.0)
Requirement already satisfied: attrs>=19.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8.21->geopandas) (21.4.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.4.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.4.0->geopandas) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.4.0->geopandas) (1.21.5)
Requirement already satisfied: zipp>=0.5 in /opt/anaconda3/lib/python3.9/site-packages (from importlib-metadata->fiona>=1.8.21->geopandas) (3.7.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/anaconda3/lib/python3.9/site-packages (from packaging->geopandas) (3.0.4)
Installing collected packages: cligj, click-plugins, shapely, pyproj, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.9.4.post1 geopandas-0.14.0 pyproj-3.6.1 shapely-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import geopandas as gpd

In [9]:
df = pd.read_csv('bloodtypes.csv')

In [10]:
df.head()

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,AB- Population
0,Albania,3074579,34.1,31.20,14.5,5.20,6.0,5.50,2.6,0.90,27671.0
1,Algeria,43576691,40.0,30.00,15.0,4.25,6.6,2.30,1.1,0.75,326825.0
2,Argentina,45479118,48.9,31.54,8.0,2.45,4.9,3.16,0.8,0.25,113698.0
3,Armenia,3021324,29.0,46.30,12.0,5.60,2.0,3.70,1.0,0.40,12085.0
4,Australia,25466459,38.0,32.00,12.0,4.00,7.0,6.00,2.0,1.00,254665.0

In [11]:
# Get the unique names of the countries in the 'Country' column
unique_countries = df['Country'].unique()

# Print the names of the countries
print("Countries in the dataset:")
for country in unique_countries:
    print(country)

Countries in the dataset:
Albania
Algeria
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahrain
Bangladesh
Belarus
Belgium
Bhutan
Bolivia
Bosnia and Herzegovina
Brazil
Bulgaria
Burkina Faso
Cambodia
Cameroon
Canada
Chile
China
Colombia
Costa Rica
Croatia
Cuba
Cyprus
Czech Republic
Democratic Republic of the Congo
Denmark
Dominican Republic
Ecuador
Egypt
El Salvador
Estonia
Ethiopia
Fiji
Finland
France
Gabon
Georgia
Germany
Ghana
Greece
Guinea
Honduras
Hong Kong
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Ivory Coast
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Laos
Latvia
Lebanon
Libya
Liechtenstein
Lithuania
Luxemburg
Macao
Malaysia
Malta
Mauritania
Mauritius
Mexico
Moldova
Mongolia
Morocco
Myanmar
Namibia
Nepal
Netherlands
New Zealand
Nicaragua
Nigeria
North Korea
North Macedonia
Norway
Pakistan
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Romania
Russia
Saudi Arabia
Serbia
Singapore
Slovakia
Slovenia
Somalia
South Africa
South Korea
Sri Lanka
Spain
Sudan
Sweden
Switzerland
Syria
Taiwan
Thailand
Tunisia
Turkey
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uzbekistan
Venezuela
Vietnam
Yemen
Zimbabwe

In [12]:
# Count the number of unique countries in the 'Country' column
num_countries = df['Country'].nunique()
print("Number of countries in the dataset:", num_countries - 1)

Number of countries in the dataset: 124

In [13]:
missing_countries = ["Afghanistan", "Andorra", "Angola", "Antigua and Barbuda",
                     "Bahamas","Barbados", "Belize", "Benin", "Botswana", "Brunei", 
                     "Burundi", "Cape Verde", "Central African Republic", "Chad", 
                     "Comoros", "Republic of the Congo", "Djibouti","Dominica", 
                     "East Timor (Timor-Leste)", "Equatorial Guinea", "Eritrea",
                     "Eswatini", "Gambia", "Grenada", "Guatemala", "Guinea-Bissau",
                     "Guyana", "Haiti", "Kiribati","Kuwait", "Kyrgyzstan", "Lesotho", 
                     "Liberia", "Madagascar", "Malawi", "Maldives", "Mali", "Marshall Islands",
                     "Micronesia", "Monaco", "Montenegro", "Mozambique", "Nauru", "Niger", 
                     "Oman", "Palau", "Panama", "Qatar", "Rwanda", "Saint Kitts and Nevis", 
                     "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
                     "Sao Tome and Principe", "Senegal", "Seychelles", "Sierra Leone", 
                     "Solomon Islands", "South Sudan", "Suriname", "Tanzania", 
                     "Togo", "Tonga", "Trinidad and Tobago", "Tuvalu", "Vanuatu"]

In [14]:
columns = ['O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-', 'AB-']
df['Predominant'] = df[columns].idxmax(axis=1)

In [15]:
!pip install pycountry;

Collecting pycountry
  Downloading pycountry-22.3.5.tar.gz (10.1 MB)
     |████████████████████████████████| 10.1 MB 2.2 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.9/site-packages (from pycountry) (61.2.0)
Building wheels for collected packages: pycountry
  Building wheel for pycountry (PEP 517) ... done
  Created wheel for pycountry: filename=pycountry-22.3.5-py2.py3-none-any.whl size=10681833 sha256=78b040beadef24cf297ba5b68cedc677777c72af1d3af7891724b0306c68f393
  Stored in directory: /Users/liujiang/Library/Caches/pip/wheels/47/15/92/e6dc85fcb0686c82e1edbcfdf80cfe4808c058813fed0baa8f
Successfully built pycountry
Installing collected packages: pycountry
Successfully installed pycountry-22.3.5

In [16]:
!pip install pycountry-convert;

Collecting pycountry-convert
  Downloading pycountry_convert-0.7.2-py3-none-any.whl (13 kB)
Collecting repoze.lru>=0.7
  Downloading repoze.lru-0.7-py3-none-any.whl (10 kB)
Collecting pprintpp>=0.3.0
  Downloading pprintpp-0.4.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: pytest>=3.4.0 in /opt/anaconda3/lib/python3.9/site-packages (from pycountry-convert) (7.1.1)
Collecting pytest-mock>=1.6.3
  Downloading pytest_mock-3.11.1-py3-none-any.whl (9.6 kB)
Collecting pytest-cov>=2.5.1
  Downloading pytest_cov-4.1.0-py3-none-any.whl (21 kB)
Requirement already satisfied: wheel>=0.30.0 in /opt/anaconda3/lib/python3.9/site-packages (from pycountry-convert) (0.37.1)
Requirement already satisfied: pycountry>=16.11.27.1 in /opt/anaconda3/lib/python3.9/site-packages (from pycountry-convert) (22.3.5)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.9/site-packages (from pycountry>=16.11.27.1->pycountry-convert) (61.2.0)
Requirement already satisfied: attrs>=19.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (21.4.0)
Requirement already satisfied: iniconfig in /opt/anaconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (1.1.1)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (21.3)
Requirement already satisfied: pluggy<2.0,>=0.12 in /opt/anaconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (1.0.0)
Requirement already satisfied: py>=1.8.2 in /opt/anaconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (1.11.0)
Requirement already satisfied: tomli>=1.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (1.2.2)
Collecting coverage[toml]>=5.2.1
  Downloading coverage-7.3.2-cp39-cp39-macosx_10_9_x86_64.whl (199 kB)
     |████████████████████████████████| 199 kB 3.8 MB/s eta 0:00:01
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/anaconda3/lib/python3.9/site-packages (from packaging->pytest>=3.4.0->pycountry-convert) (3.0.4)
Installing collected packages: coverage, repoze.lru, pytest-mock, pytest-cov, pprintpp, pycountry-convert
Successfully installed coverage-7.3.2 pprintpp-0.4.0 pycountry-convert-0.7.2 pytest-cov-4.1.0 pytest-mock-3.11.1 repoze.lru-0.7

In [17]:
from pycountry_convert import country_name_to_country_alpha2, country_alpha2_to_continent_code

def get_continent(country_name):
    if pd.notnull(country_name):
        try:
            country_alpha2 = country_name_to_country_alpha2(country_name)
            continent_code = country_alpha2_to_continent_code(country_alpha2)
            return continent_code
        except KeyError:
            return ''
    else:
        return ''

df['Continent'] = df['Country'].apply(get_continent)

In [18]:
df.head(10)

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,AB- Population,Predominant,Continent
0,Albania,3074579,34.10,31.20,14.50,5.20,6.00,5.50,2.60,0.90,27671.0,O+,EU
1,Algeria,43576691,40.00,30.00,15.00,4.25,6.60,2.30,1.10,0.75,326825.0,O+,AF
2,Argentina,45479118,48.90,31.54,8.00,2.45,4.90,3.16,0.80,0.25,113698.0,O+,SA
3,Armenia,3021324,29.00,46.30,12.00,5.60,2.00,3.70,1.00,0.40,12085.0,A+,AS
4,Australia,25466459,38.00,32.00,12.00,4.00,7.00,6.00,2.00,1.00,254665.0,O+,OC
5,Austria,8859449,30.00,37.00,12.00,5.00,6.00,7.00,2.00,0.45,39868.0,A+,EU
6,Azerbaijan,10205810,29.80,30.00,21.10,9.00,3.30,3.40,2.40,1.00,102058.0,A+,AS
7,Bahrain,1505003,48.48,19.35,22.61,3.67,3.27,1.33,1.04,0.25,3763.0,O+,AS
8,Bangladesh,164098818,29.21,26.30,33.12,9.59,0.53,0.48,0.60,0.17,278968.0,B+,AS
9,Belarus,9441842,32.30,30.60,15.30,6.80,5.70,5.40,2.70,1.20,113302.0,O+,EU

In [19]:
df.to_csv('Bloodtype.csv', index=False)

In [20]:
from IPython.display import FileLink
FileLink('Bloodtype.csv')

/Users/liujiang/Desktop/FIT3179/Assmt2/Bloodtype.csv